MODEL:
  NAME: "segformer_mitbx"
  WEIGHTS:
  FREEZE_BN: True
DATASETS:
  SOURCE_TRAIN: "gta5_train"
  TEST: "cityscapes_val"
INPUT:
  SOURCE_INPUT_SIZE_TRAIN: (504, 770)  
  TARGET_INPUT_SIZE_TRAIN: (504, 770)  
  RRC_SCALE: (0.75, 1.25)   
  RRC_RATIO: (0.66, 2.0)    
  # ViT patch 对齐
  PATCH_MULTIPLE: 14
  BRIGHTNESS: 0.5
  CONTRAST: 0.5
  SATURATION: 0.5
  HUE: 0.2
  HORIZONTAL_FLIP_PROB_TRAIN: 0.5   
SOLVER:
  BASE_LR: 5e-4
  MAX_ITER: 14000
  STOP_ITER: 14000
  BATCH_SIZE: 2
  CHECKPOINT_PERIOD: 2000
TEST:
  SLIDE_STRIDE: (512,1024)
  SLIDE_WINDOW: (512, 1024)
  SIZE_TEST: (768, 1536)
DINOV2ADAPTER:
  MODEL_NAME: "dinov2_vitl14"   
  HUB_DIR: "dinov2-main/"
  LORA_R: 6
  LORA_ALPHA: 16
  LORA_DROPOUT: 0.0
  FREEZE_BACKBONE: true
  HEAD_LR_MULT: 1.0
  LORA_LR_MULT: 0.4
DTU:
  DYNAMIC: True
  Query_STEP: 5
  Query_START: 10
  META_MAX_UPDATE: 21
  EMA_WEIGHT: 0.99
  PROXY_METRIC: 'NFD'
  FIX_ITERATION: 12
TCR:
  OPEN: True
  TOPK_CANDIDATE: 0.5
  UPDATE_FREQUENCY: 3000
METAPL:
  OPEN: True
  VAL_UPDATE: 3000
  TOP_K: 0.05

